apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.group1.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.group1.serviceName }}
spec:
  {{ $podconfig := .Values.services.group1.podconfig }}
  replicas: {{ $podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.group1.serviceName }}
  minReadySeconds: {{ $podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $podconfig.maxUnavailable }}
      maxSurge: {{ $podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.group1.serviceName }} 
        component: service-hazelcast-server
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.group1.serviceName }} 
        image: {{ .Values.services.group1.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- include "resourcesDefinition" (dict "res" $podconfig.resources) | indent 8 }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }}
        - name: JDK_JAVA_OPTIONS
          value: {{ $podconfig.java_opts }}
        ports:
        - name: hazelcast
          containerPort: {{ .Values.services.group1.ports.hazelcastPort }}
        - name: receiver-eb
          containerPort: {{ .Values.services.receiver.ports.eventbusPort }}
        - name: receiver-vt
          containerPort: {{ .Values.services.receiver.ports.containerPort }}

#        readinessProbe:
#          httpGet:
#            path: {{ .Values.services.group1.healthUrl }} 
#            port: {{ .Values.services.group1.ports.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
 #       livenessProbe:
 #         httpGet:
 #           path: {{ .Values.services.group1.healthUrl }} 
 #           port: {{ .Values.services.group1.ports.containerPort }} 
 #         initialDelaySeconds: {{ .Values.probe.initialDelay }} 
 #         periodSeconds: {{ .Values.probe.period }} 
        volumeMounts:
        - name: landing-zone
          mountPath: {{ .Values.landing.mountPath }}

      volumes:
      - name: landing-zone
        persistentVolumeClaim:
          claimName: {{ .Values.landing.pvc.name }}

